---
name: 5种花分类
author: wsure
description: 5种花分类
topic: 5种花分类
algorithm: CNN
language: python3.6
virtualenv: flyai_env/bin/

framework: Tensorflow

data:
  id: FlowerClassify
  name: 5种花分类数据
  category: image

model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: url
    to_type: float
    to_shape: [-1,100,100,3]
  output:
    columns:
      - name: label
        type: int
    to_type: int
    to_shape: [-1,5]

evaluate:
  score: tensorflow_accuracy

servers:
 - id: flyai
   url: https://flyai.com
...