---
name: BelgiumTSC
author: 李渊
description: 62种交通信号标志识别
topic: 62种交通信号标志识别
algorithm: ResNet
language: python3
virtualenv: flyai_env/bin/

framework: Tensorflow

data:
  id: BelgiumTSC
  name: 62种交通信号标志识别数据集
  category: image
model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [80, 80, 3]
  output:
    columns:
      - name: label
        type: int
    to_type: float
    to_shape: [1]


servers:
  - id: flyai
    url: https://flyai.com
...